apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
spec:
  replicas: 2
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api
          # image: '{{ .Values.ecrUrl }}:{{ .Values.imageTag }}'
          image: jaskaransarkaria/cloud-platform-label-pods:test15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
              httpGet:
                scheme: HTTPS
                path: /healthz
                port: 3000
              initialDelaySeconds: 2
          volumeMounts:
            - mountPath: "/etc/ssl/certs"
              name: tmp
              readOnly: false
          env:
            - name: GIN_MODE
              value: "release"
      initContainers:
        - name: init
          # image: '{{ .Values.ecrUrl }}:{{ .Values.imageTag }}'
          image: jaskaransarkaria/cloud-platform-label-pods:init1
          volumeMounts:
          - name: ssl-certs
            mountPath: /etc/ssl/tmp
            readOnly: false
          - name: tmp
            mountPath: /artifact
            readOnly: false
      volumes:
        - name: tmp
          emptyDir: {}
        - name: ssl-certs
          secret:
            secretName: webhook-server-cert 

                    
